In [1]:
import tensorflow as tf

In [3]:
tf.constant([[1., 2., 3.], [4., 5., 6.]])

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [4]:
tf.constant(42)

<tf.Tensor: shape=(), dtype=int32, numpy=42>

In [5]:
t = tf.constant([[1., 2., 3.], [4., 5., 6.]])

In [6]:
t.shape

TensorShape([2, 3])

In [7]:
t.dtype

tf.float32

In [8]:
t[:, 1:]

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2., 3.],
       [5., 6.]], dtype=float32)>

In [9]:
t[..., 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [10]:
t[..., 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [11]:
t[:, 1]

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 5.], dtype=float32)>

In [12]:
t[:, 1, tf.newaxis]

<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
array([[2.],
       [5.]], dtype=float32)>

In [13]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [14]:
tf.square(t)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)>

In [15]:
t @ tf.transpose(t) # matrix multiplication

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[14., 32.],
       [32., 77.]], dtype=float32)>

In [16]:
t + 10

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [17]:
tf.add(t, 10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [18]:
t.__add__(10)

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[11., 12., 13.],
       [14., 15., 16.]], dtype=float32)>

In [19]:
import numpy as np

In [20]:
a = np.array([2., 4., 5.])

In [21]:
tf.constant(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2., 4., 5.])>

In [22]:
t.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [23]:
tf.square(a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 4., 16., 25.])>

In [24]:
np.square(t)

array([[ 1.,  4.,  9.],
       [16., 25., 36.]], dtype=float32)

In [25]:
tf.constant(2.) + tf.constant(40)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a float tensor but is a int32 tensor [Op:AddV2]

In [26]:
tf.constant(2., tf.constant(40., dtype='float64'))

TypeError: Cannot convert value <tf.Tensor: shape=(), dtype=float64, numpy=40.0> to a TensorFlow DType.

In [28]:
t2 = tf.constant(40., dtype=tf.float64)

In [29]:
tf.constant(2.0) + tf.cast(t2, tf.float32)

<tf.Tensor: shape=(), dtype=float32, numpy=42.0>

In [30]:
v = tf.Variable([[1., 2., 3.], [4., 5. , 6.]])

In [31]:
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [32]:
v.assign(2*v)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [33]:
v[0, 1].assign(42)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  6.],
       [ 8., 10., 12.]], dtype=float32)>

In [34]:
v[:, 2].assign([0., 1.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[ 2., 42.,  0.],
       [ 8., 10.,  1.]], dtype=float32)>

In [35]:
v.scatter_nd_update(indices=[[0, 0], [1, 2]], updates=[100., 200.])

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[100.,  42.,   0.],
       [  8.,  10., 200.]], dtype=float32)>

In [36]:
# tf strings
tf.constant(b'hello world')

<tf.Tensor: shape=(), dtype=string, numpy=b'hello world'>

In [37]:
tf.constant('cafe')

<tf.Tensor: shape=(), dtype=string, numpy=b'cafe'>

In [40]:
# tensor for representing Unicode strings
u = tf.constant([ord(c) for c in 'cafe'])

In [41]:
b = tf.strings.unicode_encode(u, 'UTF-8')

In [42]:
b

<tf.Tensor: shape=(), dtype=string, numpy=b'cafe'>

In [43]:
tf.strings.length(b, unit='UTF8_CHAR')

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [44]:
tf.strings.unicode_decode(b, 'UTF-8')

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([ 99,  97, 102, 101], dtype=int32)>

In [45]:
p = tf.constant(['Cafe', 'Coffee', 'caffe', 'コーヒー'])

In [46]:
tf.strings.length(p, unit='UTF8_CHAR')

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([4, 6, 5, 4], dtype=int32)>

In [48]:
r = tf.strings.unicode_decode(p, 'UTF8')

In [49]:
r

<tf.RaggedTensor [[67, 97, 102, 101], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 101], [12467, 12540, 12498, 12540]]>

In [50]:
print(r)

<tf.RaggedTensor [[67, 97, 102, 101], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 101], [12467, 12540, 12498, 12540]]>


In [51]:
print(r[1])

tf.Tensor([ 67 111 102 102 101 101], shape=(6,), dtype=int32)


In [52]:
r2 = tf.ragged.constant([[65, 66], [], [67]])

In [53]:
print(tf.concat([r, r2], axis=0))

<tf.RaggedTensor [[67, 97, 102, 101], [67, 111, 102, 102, 101, 101], [99, 97, 102, 102, 101], [12467, 12540, 12498, 12540], [65, 66], [], [67]]>


In [54]:
r3 = tf.ragged.constant([[68, 69, 70] ,[71], [], [72, 73]])

In [58]:
print(tf.concat([r, r3], axis=1))

<tf.RaggedTensor [[67, 97, 102, 101, 68, 69, 70], [67, 111, 102, 102, 101, 101, 71], [99, 97, 102, 102, 101], [12467, 12540, 12498, 12540, 72, 73]]>


In [59]:
r.to_tensor()

<tf.Tensor: shape=(4, 6), dtype=int32, numpy=
array([[   67,    97,   102,   101,     0,     0],
       [   67,   111,   102,   102,   101,   101],
       [   99,    97,   102,   102,   101,     0],
       [12467, 12540, 12498, 12540,     0,     0]], dtype=int32)>

In [60]:
s = tf.SparseTensor(indices=[[0, 1], [1, 0], [2, 3]],
                    values=[1., 2., 3.],
                    dense_shape=[3, 4])

In [61]:
tf.sparse.to_dense(s)

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.]], dtype=float32)>

In [62]:
s

In [64]:
s * 4

In [65]:
s + 4

TypeError: unsupported operand type(s) for +: 'SparseTensor' and 'int'

In [ ]:
array = tf.TensorArray(dtype=tf.float32, size=3)
array = array.write(0, tf.constant([1., 2.]))
array = array.write(1, tf.constant([3. , 10.]))
array = array.write(2, tf.constant([5., 7.]))
tensor1 = array.read(1)

In [69]:
tensor1

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 3., 10.], dtype=float32)>

In [71]:
array

In [72]:
array.stack()

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 0.],
       [5., 7.]], dtype=float32)>

In [73]:
a = tf.constant([[1, 5, 9]])
b = tf.constant([[5, 6, 9, 11]])
u = tf.sets.union(a, b)

In [74]:
u

In [76]:
tf.sparse.to_dense(u)

<tf.Tensor: shape=(1, 5), dtype=int32, numpy=array([[ 1,  5,  6,  9, 11]], dtype=int32)>

In [88]:
a = tf.constant([[1, 5, 9], [10, 0, 0]])

In [94]:
b = tf.constant([[5, 6, 9 ,11]])

In [95]:
c = tf.constant([[13, 0, 0, 0, 0]])

In [97]:
u = tf.sets.union(a, b)

InvalidArgumentError: Mismatched shapes [2] vs [1] [Op:DenseToDenseSetOperation]

In [98]:
def huber_fn(y_true, y_pred):
    error = y_true - y_pred
    is_small_error = tf.abs(error) < 1
    squared_loss = tf.square(error) / 2
    linear_loss = tf.abs(error) - 0.5
    return tf.where(is_small_error, squared_loss, linear_loss)

In [106]:
tf.where(False, 0.25, 0.4)

<tf.Tensor: shape=(), dtype=float32, numpy=0.4>

In [107]:
tf.where(True, 0.25, 0.4)

<tf.Tensor: shape=(), dtype=float32, numpy=0.25>

In [113]:
from tensorflow import keras
precision = keras.metrics.Precision()
precision([0, 1, 1, 1, 0, 1, 0, 1], [1, 1, 0, 1, 0, 1, 0, 1])

<tf.Tensor: shape=(), dtype=float32, numpy=0.8>

In [114]:
precision([0, 1, 0, 0, 1, 0, 1, 1], [1, 0, 1, 1, 0, 0, 0, 0])

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [115]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.5>

In [116]:
precision.variables

[<tf.Variable 'true_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>,
 <tf.Variable 'false_positives:0' shape=(1,) dtype=float32, numpy=array([4.], dtype=float32)>]

In [117]:
precision.reset_states()

In [118]:
precision.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.0>

In [119]:
def f(w1, w2):
    return 3 * w1 ** 2 + 2 * w1 * w2

In [120]:
w1, w2 = 5, 3
eps = 1e-6
(f(w1 + eps, w2) - f(w1, w2)) / eps

36.000003007075065

In [121]:
(f(w1, w2 + eps) - f(w1, w2)) / eps

10.000000003174137

In [122]:
w1, w2 = tf.Variable(5.), tf.Variable(3.)

In [123]:
with tf.GradientTape() as tape:
    z = f(w1, w2)

In [124]:
gradients = tape.gradient(z, [w1, w2])

In [125]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [132]:
with tf.GradientTape(persistent=True) as tape:
    z = f(w1, w2)

In [133]:
dz_w1 = tape.gradient(z, w1)
dz_w2 = tape.gradient(z, w2)
del tape

In [134]:
dz_w1

<tf.Tensor: shape=(), dtype=float32, numpy=36.0>

In [135]:
dz_w2

<tf.Tensor: shape=(), dtype=float32, numpy=10.0>

In [136]:
c1, c2 = tf.constant(5.), tf.constant(3.)

In [137]:
with tf.GradientTape() as tape:
    z = f(c1, c2)

In [138]:
gradients = tape.gradient(z, [c1, c2])

In [139]:
gradients

[None, None]

In [142]:
# can force tape to watch any kind of tensors
with tf.GradientTape() as tape:
    tape.watch(c1)
    tape.watch(c2)
    z = f(c1, c2)

In [143]:
gradients = tape.gradient(z, [c1, c2])

In [144]:
gradients

[<tf.Tensor: shape=(), dtype=float32, numpy=36.0>,
 <tf.Tensor: shape=(), dtype=float32, numpy=10.0>]

In [145]:
def fnew(w1, w2):
    return 3 * w1 ** 2 + tf.stop_gradient(2 * w1 * w2)

In [146]:
@tf.function
def tf_cube(x):
    return x ** 3

In [147]:
concrete_function = tf_cube.get_concrete_function(tf.constant(2.0))

In [148]:
concrete_function

<ConcreteFunction tf_cube(x) at 0x7FA00BBBDB90>

In [149]:
concrete_function(tf.constant(2.0))

<tf.Tensor: shape=(), dtype=float32, numpy=8.0>

In [150]:
concrete_function(tf.constant(3.0))

<tf.Tensor: shape=(), dtype=float32, numpy=27.0>

In [151]:
# should throw error
concrete_function(tf.constant(2))

InvalidArgumentError: cannot compute __inference_tf_cube_643 as input #0(zero-based) was expected to be a float tensor but is a int32 tensor [Op:__inference_tf_cube_643]

In [152]:
concrete_function.graph

In [153]:
ops = concrete_function.graph.get_operations()

In [154]:
ops

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'pow/y' type=Const>,
 <tf.Operation 'pow' type=Pow>,
 <tf.Operation 'Identity' type=Identity>]

In [155]:
pow_op = ops[2]

In [156]:
pow_op

<tf.Operation 'pow' type=Pow>

In [157]:
pow_op.outputs

[<tf.Tensor 'pow:0' shape=() dtype=float32>]

In [158]:
pow_op.inputs

(<tf.Tensor 'x:0' shape=() dtype=float32>,
 <tf.Tensor 'pow/y:0' shape=() dtype=float32>)

In [159]:
concrete_function.graph.get_operation_by_name('x')

<tf.Operation 'x' type=Placeholder>

In [160]:
concrete_function.graph.get_tensor_by_name('Identity: 0')

<tf.Tensor 'Identity:0' shape=() dtype=float32>

In [161]:
concrete_function.function_def.signature

name: "__inference_tf_cube_643"
input_arg {
  name: "x"
  type: DT_FLOAT
}
output_arg {
  name: "identity"
  type: DT_FLOAT
}

In [162]:
@tf.function
def tf_cube(x):
    print('x =', x)
    return x ** 3

In [163]:
result = tf_cube(tf.constant(2.0))

x = Tensor("x:0", shape=(), dtype=float32)


In [164]:
result = tf_cube(tf.constant(3.0))

In [166]:
result = tf_cube(2)

x = 2


In [167]:
result = tf_cube(3)

x = 3


In [168]:
result = tf_cube(4)

x = 4


In [169]:
result = tf_cube(tf.constant([[1., 2.]]))

x = Tensor("x:0", shape=(1, 2), dtype=float32)


In [170]:
result = tf_cube(tf.constant([[2., 2.]]))

In [171]:
@tf.function(input_signature=[tf.TensorSpec([None, 28, 28], tf.float32)])
def shrink(images):
    return images[:, ::2, ::2] # drop half the rows and columns

In [172]:
image_batch_1 = tf.random.uniform(shape=[100, 28, 28])

In [173]:
image_batch_1.shape

TensorShape([100, 28, 28])

In [174]:
image_batch_2 = tf.random.uniform(shape=[50, 28, 28])

In [175]:
image_batch_2.shape

TensorShape([50, 28, 28])

In [176]:
preprocessed_images_1 = shrink(image_batch_1)

In [177]:
preprocessed_images_1.shape

TensorShape([100, 14, 14])

In [178]:
preprocessed_images_2 = shrink(image_batch_2)

In [180]:
preprocessed_images_2.shape

TensorShape([50, 14, 14])

In [181]:
img_batch_3 = tf.random.uniform(shape=[2, 2, 2])

In [182]:
# should throw an error
shrink(img_batch_3)

ValueError: Python inputs incompatible with input_signature:
  inputs: (
    tf.Tensor(
[[[0.46195757 0.8320118 ]
  [0.5920377  0.73049617]]

 [[0.21886313 0.04759741]
  [0.34108257 0.96164715]]], shape=(2, 2, 2), dtype=float32))
  input_signature: (
    TensorSpec(shape=(None, 28, 28), dtype=tf.float32, name=None))

In [183]:
# Autograph to capture control flow
@tf.function
def add_10(x):
    for i in range(10):
        x += 1
    return x

In [184]:
add_10(tf.constant(10))

<tf.Tensor: shape=(), dtype=int32, numpy=20>

In [185]:
add_10.get_concrete_function(tf.constant(0)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'add/y' type=Const>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'add_1/y' type=Const>,
 <tf.Operation 'add_1' type=AddV2>,
 <tf.Operation 'add_2/y' type=Const>,
 <tf.Operation 'add_2' type=AddV2>,
 <tf.Operation 'add_3/y' type=Const>,
 <tf.Operation 'add_3' type=AddV2>,
 <tf.Operation 'add_4/y' type=Const>,
 <tf.Operation 'add_4' type=AddV2>,
 <tf.Operation 'add_5/y' type=Const>,
 <tf.Operation 'add_5' type=AddV2>,
 <tf.Operation 'add_6/y' type=Const>,
 <tf.Operation 'add_6' type=AddV2>,
 <tf.Operation 'add_7/y' type=Const>,
 <tf.Operation 'add_7' type=AddV2>,
 <tf.Operation 'add_8/y' type=Const>,
 <tf.Operation 'add_8' type=AddV2>,
 <tf.Operation 'add_9/y' type=Const>,
 <tf.Operation 'add_9' type=AddV2>,
 <tf.Operation 'Identity' type=Identity>]

In [186]:
@tf.function
def add_10(x):
    for i in tf.range(10):
        x += 1
    return x

In [187]:
add_10.get_concrete_function(tf.constant(0)).graph.get_operations()

[<tf.Operation 'x' type=Placeholder>,
 <tf.Operation 'range/start' type=Const>,
 <tf.Operation 'range/limit' type=Const>,
 <tf.Operation 'range/delta' type=Const>,
 <tf.Operation 'range' type=Range>,
 <tf.Operation 'sub' type=Sub>,
 <tf.Operation 'floordiv' type=FloorDiv>,
 <tf.Operation 'mod' type=FloorMod>,
 <tf.Operation 'zeros_like' type=Const>,
 <tf.Operation 'NotEqual' type=NotEqual>,
 <tf.Operation 'Cast' type=Cast>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'zeros_like_1' type=Const>,
 <tf.Operation 'Maximum' type=Maximum>,
 <tf.Operation 'while/maximum_iterations' type=Const>,
 <tf.Operation 'while/loop_counter' type=Const>,
 <tf.Operation 'while' type=StatelessWhile>,
 <tf.Operation 'Identity' type=Identity>]

In [188]:
counter = tf.Variable(0)

In [189]:
@tf.function
def increment(counter, c=1):
    return counter.assign_add(c)

In [190]:
increment(counter)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [191]:
increment(counter)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [192]:
function_def = increment.get_concrete_function(counter).function_def

In [193]:
function_def.signature.input_arg[0]

name: "counter"
type: DT_RESOURCE

In [194]:
function_def.signature

name: "__inference_increment_793"
input_arg {
  name: "counter"
  type: DT_RESOURCE
}
output_arg {
  name: "identity"
  type: DT_INT32
}
is_stateful: true
control_output: "AssignAddVariableOp"
control_output: "ReadVariableOp"

In [217]:
class MyNormalLayer(keras.layers.Layer):
    def __init__(self, eps=0.001, **kwargs):
        super().__init__(**kwargs)
        self.eps = eps
        
    def build(self, batch_input_shape):
        self.alpha = self.add_weight(name='alpha',
                                     shape=batch_input_shape[-1:], initializer='ones')
        self.beta = self.add_weight(name='beta',
                                    shape=batch_input_shape[-1:], initializer='zeros')
        super().build(batch_input_shape)
        
    def call(self, X):
        mean, variance = tf.nn.moments(X, axes=-1, keepdims=True)
        return self.alpha * ((X - mean)/tf.sqrt(variance) + self.eps) + self.beta
    
    def compute_output_shape(self, batch_input_shape):
        return batch_input_shape
    
    def get_config(self):
        base_config = super().get_config()
        return {**base_config, "eps": self.eps}

In [218]:
mnist = keras.datasets.mnist.load_data()
(X_train_full, y_train_full), (X_test, y_test) = mnist
X_train_full = X_train_full.astype(np.float32) / 255.
X = X_train_full.astype(np.float32)

In [219]:
custom_normal_layer = MyNormalLayer()
keras_normal_layer = keras.layers.LayerNormalization()

In [220]:
tf.reduce_mean(keras.losses.mean_absolute_error(
    custom_normal_layer(X), keras_normal_layer(X)))

<tf.Tensor: shape=(), dtype=float32, numpy=nan>