In [5]:
import numpy as np
from sklearn import datasets
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import LinearSVC

In [6]:
iris = datasets.load_iris()

In [7]:
X = iris['data'][:, (2, 3)] # petal length, petal width
y = (iris['target'] == 2).astype(np.float64) # Iris virginica

In [10]:
svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('linear_svc', LinearSVC(C=1, loss='hinge'))
])

In [11]:
svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('linear_svc', LinearSVC(C=1, loss='hinge'))])

In [12]:
svm_clf.predict([[5.5, 1.7]])

array([1.])

In [13]:
from sklearn.datasets import make_moons
from sklearn.preprocessing import PolynomialFeatures

In [15]:
X, y = make_moons(n_samples=100, noise=0.15)

In [16]:
polynomial_svm_clf = Pipeline([
    ('poly_features', PolynomialFeatures(degree=3)), 
    ('scaler', StandardScaler()),
    ('svm_clf', LinearSVC(C=10, loss='hinge'))
])

In [17]:
polynomial_svm_clf.fit(X, y)

Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf', LinearSVC(C=10, loss='hinge'))])

In [18]:
from sklearn.svm import SVC

In [19]:
poly_kernel_svm_clf = Pipeline([
    ('scaler', StandardScaler()),
    ('svm_clf', SVC(kernel='poly', degree=3, coef0=1, C=5))
])

In [20]:
poly_kernel_svm_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=5, coef0=1, kernel='poly'))])

In [21]:
polynomial_svm_clf.predict([[5.5, 1.7]])

array([1])

In [22]:
poly_kernel_svm_clf.predict([[5.5, 1.7]])

array([1])

In [23]:
rbf_kernel_smv_clf = Pipeline([
    ('scaler', StandardScaler()), 
    ('svm_clf', SVC(kernel='rbf', gamma=5, C=0.001))
])

In [24]:
rbf_kernel_smv_clf.fit(X, y)

Pipeline(steps=[('scaler', StandardScaler()),
                ('svm_clf', SVC(C=0.001, gamma=5))])

In [25]:
rbf_kernel_smv_clf.predict([[5.5, 1.7]])

array([0])

In [26]:
from sklearn.svm import LinearSVR

In [27]:
svm_reg = LinearSVR(epsilon=1.5)

In [28]:
svm_reg.fit(X, y)

LinearSVR(epsilon=1.5)

In [29]:
svm_reg.fit(X, y)

LinearSVR(epsilon=1.5)

In [30]:
svm_reg.predict([[5.5, 1.7]])

array([0.])

In [31]:
from sklearn.svm import SVR

In [32]:
svm_poly_reg = SVR(kernel='poly', degree=2, C=100, epsilon=0.1)
svm_poly_reg.fit(X, y)

SVR(C=100, degree=2, kernel='poly')